### ISSUE TITLE
Videomode development

### ISSUE THREAD

**Issue by CJvanDiepen** [QuTech-Delft/qtt#22]
ToDo extensions of the videomode:

- [x] Get coordinates via mouse click callback
- [x] Running average / Continue averaging until event occurs
- [x] Naverage in GUI
- [x] Marker at the center to show your current position?

Wishlist:

- [ ] "Click and drag"
- [ ] Add lines to live plot
- [ ] Save current image with higher averaging, hence higher SNR
- [ ] Change AWG amplitude while sweeping to change the sweeprange
- [ ] Measure and tune sensing dot directly from 2d scan, possibly via push button
- [ ] Set all gates to zero with push button

**Comment by peendebak** [comment]
Todo has been implemented, wishlist deferred to VideoMode 2.0
