### ISSUE TITLE
Closing VideoMode window without stopping causes unexpected behaviour

### ISSUE THREAD

**Issue by spmvg** [QuTech-Delft/qtt#429]
If I (accidentally) close the VideoMode (`qtt.measurements.videomode.VideoMode`) without pressing the stop button, the behaviour of the rest of the code is unexpected. For example, all AWGs keep running and if I then immediately shut off all communications afterwards (sorry for my setup-specific code):

```
rfa.off()
rfb.off()
awg.stop()
wet_8dot.close()
```

I will get the following error:

```
ERROR:root:could not find instrument digitizer
Traceback (most recent call last):
  File "d:\users\cjvdiepen\qtt\qtt\measurements\videomode.py", line 342, in updatebg
    dd = self.datafunction()
  File "d:\users\cjvdiepen\qtt\qtt\measurements\videomode.py", line 69, in __call__
    minstrumenthandle = qtt.measurements.scans.get_instrument(self.minstrument)
  File "d:\users\cjvdiepen\qtt\qtt\measurements\scans.py", line 249, in get_instrument
    raise Exception('could not find instrument %s' % str(instr))
Exception: could not find instrument digitizer
VideoMode: Exception in updatebg, stopping readout
VideoMode: stop readout
```

I'm unsure if closing the window without stopping is a feature or a bug, but I would expect the VideoMode to execute the closing routine when I close the window?

Kind regards,
Steven

**Comment by peendebak** [comment]
Actually, the behaviour is as it should be: you remove an instrument (by closing the station) and then the Videomode reports that:
1. It could not find the instrument 
2. It stops the readout

The AWGs keep indeed running, but that is not something I would want to change. (general guideline: if there is an error, stop directly and let the user decide what to do). You could stop the AWGs when the station is closed. If you want that, you can do it in your own station setup.

@spmvg
