### ISSUE TITLE
VideoMode: separate GUI from awg commands

### ISSUE THREAD

**Issue by dpfranke** [QuTech-Delft/qtt#480]
Can we separate the VideoMode GUI from the commands that program the AWG for the fast maps? I would like to use it for our transport maps in the Ge system, but would prefer to keep our own upload code. In general, I am reluctant to run any code that talks to the AWG and/ or DACs without exactly knowing what it will do. Therefore, it would be great if the more 'dangerous', hardware specific code could be put together more clearly. For example, the preparation / uploading / running of the AWG could be separated into a few functions such that I can define a child class and overwrite those? That would also make the code more readable, imho. Even nicer would be the definition of a generic videomode class, with subclass-defined prepare, run, read etc functions...

@peendebak @lucblom @fvanriggelen

**Comment by peendebak** [comment]
A beginning of making a better separation was done in #594.
