### ISSUE TITLE
Add tqdm to condalist

### ISSUE THREAD

**Issue by jpdehollain** [QuTech-Delft/qtt#508]
The latest version of `qcodes` requires the package `tqdm`. Consider adding it to `condalist.yml`

**Comment by eendebakpt** [comment]
@jpdehollain 'tqdm' is already part of the qcodes requirements, adding it to the `condalist.yml` will not solve the issue. The issue is that people update qcodes with a git pull, but do not update the required packages. We need another solution to solve this gracefully.

@CumulonimbusCalvus
