### ISSUE TITLE
Polygon3 is not compatible with Python 3.7

### ISSUE THREAD

**Issue by CumulonimbusCalvus** [QuTech-Delft/qtt#579]
@peendebak @QFer 

Is the module Polygon3 only used here:
https://github.com/QuTech-Delft/qtt/blob/b91d85664a6ddf82b483cda29243ac46dd171bea/src/qtt/pgeometry.py#L1156

?

**Comment by QFer** [comment]
Hmm, looks like you're right
only polyintersect uses it.

**Comment by QFer** [comment]
By the way, I found binaries for polygon on windows python 3.7 on:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by CumulonimbusCalvus** [comment]
The source can be found here: https://bitbucket.org/jraedler/polygon3/src/master/

**Comment by peendebak** [comment]
@QFer The binaries on https://www.lfd.uci.edu/~gohlke/pythonlibs/ are in general of good quality.  However, they do not install from pip, so I prefer alternative solutions.

[Shapely ](https://pypi.org/project/Shapely) has similar capabilities (it was used in the first versions of qtt), but does not provide windows installers. They are there for anaconda, not for a plain windows virtualenv.

**Comment by jpdehollain** [comment]
@peendebak @QFer hi guys, any progress on this? Trying to install qtt on my new machine, seems like Polygon3 is available for 3.7 now, but requires Visual C++ 14.0, which is a pain to find and install, and it's 3GB. This is a bit ridiculous for a couple of functions that most users probably won't use.

**Comment by QFer** [comment]
@jpdehollain Hi, I installed the compiled binary I got from: https://www.lfd.uci.edu/~gohlke/pythonlibs/ 
the 64bit wheel package is called: Polygon3-3.0.8-cp37-cp37m-win_amd64.whl
>pip install Polygon3-3.0.8-cp37-cp37m-win_amd64.whl will do
When you don't have wheel do:
>pip install wheel

**Comment by eendebakpt** [comment]
We could replace the code by extracting code from https://github.com/heineman/python-polygon-intersection/tree/master/Polygon. This is python only, so no dependencies.

**Comment by philomathie** [comment]
I just wanted to bring this up again, as I also had issues installing it. In the end, using the compiled binaries from gohlke worked, but it's not nice to be so hacky.

I should also mention that I attempted to get QTT working with Python 3.8, but it seemed there were additional complications as the requirements for QTT was very unhappy with the use of a Polygon3 3.8 build.

**Comment by QFer** [comment]
Closed because this is already fixed in https://github.com/QuTech-Delft/qtt/pull/744
