### ISSUE TITLE
feature requests parameter viewer

### ISSUE THREAD

**Issue by stephanlphilips** [QuTech-Delft/qtt#595]
The parater viewer is quite a handy tool to manage the voltages on the samples, but sometimes there are a few issues that make it harder to work with. The following things are missing a bit for our measurements at the moment (these should be quite useful for all users):

- are you sure notification if you make big jumps (e.g. > 200mV) (example scenario if you wanted to go to 200 mV but accidentally pressed 2000)
- true multithreading/processing (so no hanging of the parameter viewer anymore), set voltages during the measurement. 
- Tab with virtual gates (one for every real one)
- Tab with settings (e.g. step taken when pressing up a voltage, stepsize of the dacs, boundaries, ...)

**Comment by peendebak** [comment]
@stephanlphilips @CumulonimbusCalvus @QFer 

There is already a parameterviewer that can show settings in [pycqed](https://github.com/DiCarloLab-Delft/PycQED_py3):
```
from pycqed.instrument_drivers.virtual_instruments.instrument_monitor import InstrumentMonitor
im = InstrumentMonitor('monitor', station)
```
(downside is that you cannot set values with this one)

To make parameterviewer 'true multithreading'  the instrument drivers should be as well. QCoDeS instruments are not multi-thread safe (and there is no multi-processing variant), so adding this feature is quite hard. 

The notification for big jumps is is handled partly by the boundaries you can set on QCoDeS parameters. But adding an extra notification to the GUI indeed seems like a  good option to have.

**Comment by peendebak** [comment]
The QTT parameterviewer has been replaced by new tools. Closing the issue.
