### ISSUE TITLE
QCoDeS update breaks QTT installation

### ISSUE THREAD

**Issue by CumulonimbusCalvus** [QuTech-Delft/qtt#604]
Recent PR: https://github.com/QCoDeS/Qcodes/pull/1633 changes the version name to something like 0.4.0+30.g160bfbc45. This is not working with the QTT setup.py installer because the StrictVersion function cannot handle these type of versions.

How to resolve?

**Comment by CumulonimbusCalvus** [comment]
@peendebak 

We could change it to LooseVersion from distutils?

**Comment by peendebak** [comment]
Fixed by #597  (suggested on qcodes slack)

**Comment by CumulonimbusCalvus** [comment]
Fixed by #606.
