### ISSUE TITLE
Problem installing PyQt5

### ISSUE THREAD

**Issue by mjwoudstra** [QuTech-Delft/qtt#611]
Doing an install from scratch using:
`python setup.py develop`
 I encounter the following error message:
`pyqtgraph plotting not supported, try "from qcodes.plots.pyqtgraph import QtPlot" to see the full error`

When I do as suggested I get:

`>>> from qcodes.plots.pyqtgraph import QtPlot
pyqtgraph plotting not supported, try "from qcodes.plots.pyqtgraph import QtPlot" to see the full error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<envdir>\lib\site-packages\qcodes\plots\pyqtgraph.py", line 6, in <module>
    import pyqtgraph as pg
  File "<envdir>\lib\site-packages\pyqtgraph-0.10.0-py3.6.egg\pyqtgraph\__init__.py", line 13, in <module>
    from .Qt import QtGui
  File "<envdir>\lib\site-packages\pyqtgraph-0.10.0-py3.6.egg\pyqtgraph\Qt.py", line 153, in <module>
    from PyQt5 import QtGui, QtCore, QtWidgets, uic
ModuleNotFoundError: No module named 'PyQt5.sip'`

Looking around on the internet I found that the issue is that PyQt5 is now split into 2 packages: pyqt5 and pyqt5-sip, which are not working together as they should. A workaround is to install PyQt5 with:
`pip install -I pyqt5`
before installing qtt. Ideally we incorporate this in setup.py, but I don't know how.

**Comment by peendebak** [comment]
@mjwoudstra Perhaps we can update the installation instructions to use `pip install -r requirements.txt -e .` instead of `python setup.py develop`. That should fix the issue.
Can you try that? And if it doesn't work, report the python version and distribution.

For reference: the split of PyQt5 is discussed here https://coldfix.de/2019/03/14/no-pip-no-sip/

**Comment by CumulonimbusCalvus** [comment]
The error is generated by qcodes. QTT has qcodes as a dependency in the setup as an install requirement. There idea is that not all qcodes users want to use the plotting functionality and have PyQt5 (big package) installed by default.

I agree that after installing QTT it should just work without having any errors or other needed packages. Would be nice to update the `setup.py` such that it works. What do you think @peendebak? 

This holds also for other packages which are not even in the requirements.txt like `opencv-python`.

**Comment by peendebak** [comment]
`PyQt5` is installed by default now, closing the issue
