### ISSUE TITLE
Problem installing pyqtgraph

### ISSUE THREAD

**Issue by mjwoudstra** [QuTech-Delft/qtt#612]
pyqtgraph is in the `install_requires` list in `setup.py` without any version requirement. This downloads version 0.10 (latest available release). However, version 0.11 is the minimum (as specified in `extras`). If this version requirement is also added to the `install_requires` list (as it should be for consistency), that fails because 0.11 does not exist (anywhere). As a workaround, we can download the develop branch from github by adding an extra parameter to the setup() call:

`dependency_links=[
        'git+https://github.com/pyqtgraph/pyqtgraph@develop#egg=pyqtgraph'
],`

The version number should in that case still be omitted from`install_requires`, because setup() does not properly parse the develop version (0.11.0.dev0+gad7453c) and the >=0.11 check fails. 
pyqtgraph should also be removed from extras (no longer needed, and version check fails).

**Comment by peendebak** [comment]
@mjwoudstra Qtt works with pyqtgraph 0.10. The 0.11 version was only required for part of the functionality, but I am not sure that is valid currently. Once pyqtgraph 0.11 is released officially we should update to 0.11
