### ISSUE TITLE
Installation fails because pyqtgraph requires PyQt5

### ISSUE THREAD

**Issue by mjwoudstra** [QuTech-Delft/qtt#616]
After the fix applied in pull request "[OP-61] Improve qtt installation." installation of pyqtgraph still fails, but for a different reason.
`pip install -e .`  fails because pyqtgraph needs PyQt5, which is not in the requirements list. This can be solved by adding pyqt5 to the `install_requires` list in setup.py.

[OP-61]: https://qutech-sd.atlassian.net/browse/OP-61

**Comment by CumulonimbusCalvus** [comment]
Duplicated by  #611, which is indeed not resolved.
