### ISSUE TITLE
virtualAWG not turning on all channels

### ISSUE THREAD

**Issue by NicoHendrickx** [QuTech-Delft/qtt#639]
When using the virtualAWG in video-mode, using virtual gates. Using a virtual gate space that uses (ch1,ch3) for x-axis and (ch2,ch4) for the y-axis. All the proper waveforms are generated, but for some reason, channel 4 does not get enabled. When turned on manually, everything works fine, but this is slightly annoying.

**Comment by peendebak** [comment]
@NicoHendrickx Some questions:

* Are you using the old or new virtual awg?
* After starting the videomode, can you post the contents of videomode.videomode_processor.waveform?
* Can you try #644

**Comment by NicoHendrickx** [comment]
@peendebak 

_- Are you using the old or new virtual awg?_
The new one.

- After starting the videomode, can you post the contents of videomode.videomode_processor.waveform?
The waveform is fine.

- Can you try #644
This does not work, however the fix is:
Change line 380 to:
`keys = qtt.utilities.tools.flatten(gates)`

**Comment by peendebak** [comment]
@NicoHendrickx Can you check what the contents of `gates` is at that specific line of code? I would expect something like `gates=[{'P1': 1, 'P2': 3.}, {'P3': 6, 'P1': -2}]`, and then `keys = qtt.utilities.tools.flatten(gates)` is equal to the code from the PR.

**Comment by NicoHendrickx** [comment]
That's correct, I forgot to remove the [0] from the code in replicating the PR. My bad. PR works as well.
