### ISSUE TITLE
exampledata folder seems to not be cloned

### ISSUE THREAD

**Issue by bogdanvconstantin** [QuTech-Delft/qtt#715]
I installed qtt as a site-package part of another package.

In my setup.py I have:

```
qtt = 'qtt @ git+ssh://git@github.com/QuTech-Delft/qtt#egg=qtt'
...
setup(
    ...
    install_requires = [ ..., qtt, ...]
    ...
    )
```

However, it seems that after the installation completes successfully (after a `pip install .`)the qtt/exampledata/ folder is not part of my qtt site-packages. 

![Uploading Screenshot 2020-02-23 at 20.08.09.png…]()

Can someone please have a look at this? 
Thank you!

**Comment by peendebak** [comment]
The exampledata should be accesible with 
```
import qtt.data
dataset=qtt.data.load_example_dataset('time_rabi_scan.json')
```
The `load_example_dataset` is used in several example notebooks, e.g. https://qtt.readthedocs.io/en/latest/notebooks/analysis/example_fermi_fitting.html
@sldesnoo-Delft @QFer

**Comment by QFer** [comment]
When installing qtt via 'pip install .' only the qtt 'functionality' is installed, not the docs, ipython notebooks etc. So in my opinion exampledata is also one of the components that should not be installed. When you want to run examples or unit tests you have to install in editable mode.

Or am I missing something?

**Comment by sldesnoo-Delft** [comment]
@QFer You've got a good point. I tend to agree and we should remove the docs and examples from the install.
@peendebak Do you agree?

**Comment by sldesnoo-Delft** [comment]
See #721

**Comment by QFer** [comment]
Closed because this issue is solved in https://github.com/QuTech-Delft/qtt/pull/750
