### ISSUE TITLE
Add set of example data of qtt distribution

### ISSUE THREAD

**Issue by sldesnoo-Delft** [QuTech-Delft/qtt#721]
qtt should provide a set of example measurement data of common measurements. This data can be used as input during development and demonstration, also for code that is not part of qtt.

There is already some example data, but it is not included in the distribution and does not have descriptive names.

Changes to be made:
* Include example data in distribution
* Change names to descriptive ones
* Add a function to retrieve the names of the available examples

Rename:
"addition_line_scan" Old name: '17-57-24'
"charge_stability_diagram_anti_crossing" Old name: '2017-01-10/09-45-15'
"polarization_line" Old name: '2017-02-21/15-59-56'
"charge_stability_diagram_anti_crossing_virtual_gates" Old name: '2017-09-04/11-04-14_qtt_scan2Dturbovec'
"PAT_scan_background" Old name: '2017-09-04/11-04-45_qtt_scan1Dfastvec'
"PAT_scan" Old name: '2017-09-04/11-05-17_qtt_scan2Dfastvec'
"coulomb_peak" Old name: 'misc/13-13-16_qtt_sensingdot_t.fastTune'
"charge_stability_diagram_double_dot_system" Old name: 'misc/Lever_arm_Charging_energy/10-06-59_qtt_scan2Dfast' (and perhaps resample to make loading faster)
"charge_stability_diagram_double_dot_system_detail" Old name: 'misc/Lever_arm_Charging_energy/14-28-52_qtt_scan2Dfast'
"charge_stability_diagram_double_dot_system_bias_triangle" Old name: 'misc/Lever_arm_Charging_energy/14-33-26_qtt_scan2Dfast'
"pinchoff_scan_barrier_gate" Old name: 'misc/pinchoff/2018-06-28/13-24-22_qtt_scan1D'
"2electron_pat_background" Old name: 'misc/2electron_pat_26102017/background'
"2electron_pat" Old name: 'misc/2electron_pat_26102017/pat'
"elzerman_detuning_scan" Old name: 'elzerman_detuning_scan/2019-05-28_11-39-39_qtt_generic.json'
'charge_stability_diagram_dac_vs_awg' Old name 'misc/P5_y_P5_x.dat'
'rts_signal' Old name '2018-08-31/19-05-18_qtt_save_segments'

Name already good:
'time_rabi_scan.json'
'frequency_rabi_scan.json'
'double_gaussian_dataset.json'

To be removed from repository:
'misc/awg_to_plunger_scan.pickle'

@eendebakpt, I've extracted the renaming from your email.

**Comment by QFer** [comment]
Closed because this issue is solved in: https://github.com/QuTech-Delft/qtt/pull/750
