### ISSUE TITLE
scikit-image release breaks qtt

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/qtt#740]
Scikit-image 0.17 was released with some non-backwards compatible changes to `peak_local_max` (https://github.com/scikit-image/scikit-image/pull/4501). The qtt tests are broken, and probably the functionality as well.

@QFer @sldesnoo-Delft

**Comment by QFer** [comment]
The unit tests that used peak_local_max result didn't take into account that the order of peak_local_max is not defined. The same peaks were found but were returned in a different order in the new version.
