### ISSUE TITLE
Pauli spin blockade or readout with a resonator

### ISSUE THREAD

**Issue by mattcu64** [QuTech-Delft/qtt#863]
Hi, 

I am looking at the notebook 'Simulation of Elzerman readout' under 'Example notebooks/analysis'. 
At the last part, it shows an example of the Pauli spin blockade readout to detect 'singlet' or 'triplet'. However, I am confused that  the triplets transfer to singlets after some time and then be detected. 

Could you describe more specifically what kind of resonator it is and how's the system initialised?

The whole repository is great. Looking forward to hearing from you.

Thanks.

**Comment by peendebak** [comment]
@mattcu64 Triplets decay to singlets on a typical timescale of T1 which is 3 milisecond in this example. 

Note that this is a pure simulation, so there is no resonator involved.

The initialization for each trace is random (e.g. the argument `initial_state=[0.5,0.5]`)
