### ISSUE TITLE
QTT code should be updated to be compatible with Python 3.11

### ISSUE THREAD

**Issue by QFer** [QuTech-Delft/qtt#868]
* QTT code should be updated to be compatible with Python 3.11

**Comment by eendebakpt** [comment]
@bkreynen @QFer  With #874 merged we can close this one (preferably with also updating the pypi package)

**Comment by bkreynen** [comment]
@eendebakpt I started releasing the pypi package yesterday but noticed a lot of remaining warnings when running the tests. I created a PR to fix the ones that were easy to fix for me (https://github.com/QuTech-Delft/qtt/pull/875).

**Comment by bkreynen** [comment]
@eendebakpt I continued with the release today but encountered an error when running on Linux with Python 3.8. I created a PR for a fix: https://github.com/QuTech-Delft/qtt/pull/876. I will continue working on the release on Monday if the PR has been approved by then.

**Comment by bkreynen** [comment]
@eendebakpt I started working on the release again today but a new version of QCodes was released on Wednesday. This new version introduced some new errors and warnings in QTT. I created a PR for this (hopefully last) fix: https://github.com/QuTech-Delft/qtt/pull/877

**Comment by bkreynen** [comment]
Released with qtt 1.4.0
